version: '3.0'

services: 
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: tlc
      MYSQL_USER: tlc
      MYSQL_PASSWORD: tlc
      MYSQL_ROOT_PASSWORD: tlc
    ports:
      - 3306:3306
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10

  # api: 
  #   depends_on: 
  #     mysql:
  #       condition: service_healthy
  #   image: api
  #   build: ./api