version: "3.0"

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    ports:
      - "80:80"
      - "443:443"
    restart: always
    depends_on:
      - api
      - etherpad
      - front

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

  mysql-docker:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: tlc
      MYSQL_USER: tlc
      MYSQL_PASSWORD: tlc
      MYSQL_ROOT_PASSWORD: tlc
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  api:
    depends_on:
      mysql-docker:
        condition: service_healthy
      etherpad:
        condition: service_healthy
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:mysql://mysql-docker:3306/tlc?useUnicode=true&serverTimezone=Europe/Paris
      DOODLE_INTERNALPADURL: http://etherpad:9001/
      DOODLE_EXTERNALPADURL: http://projettlchf.istic.univ-rennes1.fr/etherpad/
      QUARKUS_FLYWAY_MIGRATE_AT_START: true
      QUARKUS_MAILER_HOST: mailer
      QUARKUS_MAILER_PORT: 25
    image: api
    build: ./api

  etherpad:
    image: etherpad/etherpad
    volumes:
      - "./APIKEY.txt:/opt/etherpad-lite/APIKEY.txt"

  front:
    image: front
    build: ./front
    volumes:
      - ./nginx.front.conf:/etc/nginx/conf.d/default.conf:ro

  mailer:
    image: bytemark/smtp
    restart: always

  myadmin:
    image: phpmyadmin
    container_name: myadmin
    environment:
      - PMA_HOST=mysql-docker
      - PMA_ABSOLUTE_URI=http://projettlchf.istic.univ-rennes1.fr/phpmyadmin/
